[project]
name = "opycities"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astropy>=7.0.0",
    "fprettify>=0.3.7",
    "numpy>=2.2.0",
]
